[window]
padding = { x = 10, y = 10 }
decorations = "full"
opacity = 1.0
blur = false

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
size = 12.0

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black = "#1e1e2e"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cdd6f4"

[colors.bright]
black = "#313244"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cdd6f4"

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor.vi_mode_style]
shape = "Block"

[terminal.shell]
program = "/bin/zsh"
# Allow programs to change the window title
args = ["--login"]

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]
